<h1 class="text-danger">movies here</h1>

<div class="row">
    <div class="col-md-4 p-3 d-flex flex-column">
        <form action="/movies/add" class="d-flex flex-column" method="post">
            <input type="text" name="movie_name" class="m-2" placeholder="movie name" required>
            <input type="text" name="movie_type" class="m-2" placeholder="movie type" required>
            <input type="submit" name="submit" class="m-2">
        </form>
    </div>
</div>